--1. CREATE DATABASE 
CREATE DATABASE Round61
GO
USE Round61
GO
DROP DATABASE Round61
GO
--2. CREATE DATABASE
IF NOT EXISTS(
SELECT NAME
FROM SYS.DATABASES
WHERE NAME=N'Round61'
)
CREATE DATABASE Round61
GO
--3. CREATE DATABASE
CREATE DATABASE IsDB
ON(
NAME='IsDB_1',
FILENAME='D:\SQL\IsDB_1.mdf',
SIZE=2MB,
MAXSIZE=50,
FILEGROWTH=10%
)
LOG ON(
NAME='IsDBlog_1',
FILENAME='D:\SQL\IsDBlog_1.ldf',
SIZE=2MB,
MAXSIZE=50,
FILEGROWTH=1MB
)
GO
DROP DATABASE IsDB

SELECT 1+2
GO
SELECT 5*6 'MUL'
GO
SELECT @@SERVERNAME 'SERVER'
GO
EXECUTE sp_helpdb 'Round61'
GO
EXEC sp_helpdb 'IsDB'
GO
--CREATE TABLE
CREATE TABLE Student
(
Id INT,
Name VARCHAR(30)
)
GO
SELECT * FROM Student
GO
--INSERT DATA
INSERT INTO Student(ID,Name)
VALUES(1,'Rina')
GO
--INSERT MULTI DATA
INSERT INTO Student(ID,Name)
VALUES(2,'Tina'),
	(3,'Bina')
GO
--INSERT TABLE
CREATE TABLE Trainees(
Id INT,
Name VARCHAR(30),
Email VARCHAR(30),
Phone VARCHAR(30)
)
GO
SELECT * FROM Trainees
GO
--INSERT DATA
INSERT INTO Trainees(Id,Name,Email,Phone)
VALUES(1,'Rina','Rina@gmail.com','01215454'),
(2,'Bina','Bina@gmail.com','01215454'),
(3,'Tina','Tina@gmail.com','01215454')

CREATE DATABASE Commands
GO
USE Commands
GO

--TABLE CREATE
CREATE TABLE Student(
Id INT,
Name VARCHAR(30)
)
GO
--DATA RITRIVE
SELECT * FROM Student
GO
--INSERT COMMAND
INSERT INTO Student(Id,Name)
VALUES(1,'Rina')

--INSERT MULTI COMMAND
INSERT INTO Student(Id,Name)
VALUES(2,'Bina'),
	(3,'Tina')
	GO

	--UPDATE COMMAND
	UPDATE Student
	SET Name='Mina'
	WHERE Id=2
	GO

	--DELETE COMMAND
	DELETE FROM Student
	WHERE Id=2
	GO

	--ALTER CAMMAND
	ALTER TABLE Student
	ADD Email VARCHAR(30)
	GO
	--DROP COMMAND
	DROP TABLE Student
	GO

	--GRANT COMMAND
	GRANT SELECT, UPDATE ON Student TO Samaul
	GO
	--REVOKE COMMAND
	REVOKE SELECT, UPDATE, DELETE ON Student FROM Samaul